# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f9619ec58adaaf45178adfdb911b30e13d12374fb8fa82e2eeb8384e002b594b1d0c439405f0439e339cba8330f796825f53d63f37d2a2f33c4568165ca238d

test:
  secret_key_base: aa74cd4252f5d7adab0ca247139bb1debf5cc5f3279a67a3aa82f219cfe236e30c2e11f2caf55b830cfd2a86db85fdb195eb542ce7f309a0c1e017b21c8ef355

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
